### ISSUE TITLE
Encaminhamento para perfil errado

### ISSUE THREAD

**Issue by Camesis** [JuliodsGarcia/JuliodsGarcia#1]
Os ícones para contato estão com o endereçamento para o perfil de outra pessoa :c 

Ex de trecho citado: 
` <a href="https://www.instagram.com/edu.duduribeiro/ " target="_blank"><img src="https://img.shields.io/badge/-Instagram-%23E4405F?style=for-the-badge&logo=instagram&logoColor=white" target="_blank"></a>`

**Comment by JuliodsGarcia** [comment]
Olá Camila, tudo bem?

obrigado pelo feedback, alteração já realizada.

Atenciosamente
Julio Garcia.

Em ter., 11 de abr. de 2023 às 23:06, Camila Correia <
***@***.***> escreveu:
